### ISSUE TITLE
Things to fix and/or to implement

### ISSUE THREAD

**Issue by skid9000** [anjaraeu/Raki#1]
As discussed at the "General Assembly" the 08/08/19 :

- [ ] Trying to upload big files from mobile doesn't work (over 1GB).
- [x] Add the possibility to admins to set the max expiration delay from the size of files. (.env ?)
- [x] Add the possibility to admins to set the maximum size of files. (.env ?)

**Comment by Luclu7** [comment]
You can now set the max size of files with MIX_MAX_FILE_SIZE in the .env, in megabytes.

**Comment by theo33500** [comment]
see #2 for revamp
